apiVersion: v1
kind: Service
metadata:
  name: ipfs-svc
  labels:
    app: ipfs
spec:
  type: LoadBalancer
  ports:
    - name: http-server
      port: 8080
      targetPort: 8080
    - name: swarm
      port: 4001
      targetPort: 4001
    - name: webui
      port: 5001
      targetPort: 5001
  selector:
    app: ipfs
