apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-export-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  volumes:
  - name: ipfs-data
    persistentVolumeClaim:
      claimName: ipfs-data-pvc
  - name: ipfs-export
    persistentVolumeClaim:
      claimName: ipfs-export-pvc
  containers:
  - name: ipfs
    image: harbor.filcloud.io:2443/filcloud/go-ipfs:latest
    imagePullPolicy: Always
    ports:
      - name: http-server
        containerPort: 8080
      - name: webui
        containerPort: 5001
      - name: swarm
        containerPort: 4001
    env:
      - name: IPFS_CORS_ORIGIN
        value: http://192.168.0.231:5001
    volumeMounts:
    - name: ipfs-data
      mountPath: /data/
    - name: ipfs-export
      mountPath: /export/
