apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-export-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  volumes:
  - name: ipfs-data
    persistentVolumeClaim:
      claimName: ipfs-data-pvc
  - name: ipfs-export
    persistentVolumeClaim:
      claimName: ipfs-export-pvc
  containers:
  - name: ipfs
    image: ipfs/go-ipfs:latest
    imagePullPolicy: Always
    ports:
      - name: http-server
        containerPort: 8080
      - name: webui
        containerPort: 5001
      - name: swarm
        containerPort: 4001
    env:
      - name: LOTUS_STORAGE_PATH
        value: /data/lotusstorage
      - name: LOTUS_PATH
        value: /data/lotus
      - name: FULLNODE_LISTEN_ADDR
        value: /ip4/0.0.0.0/tcp/1234/http
    volumeMounts:
    - name: ipfs-data
      mountPath: /data/
    - name: ipfs-export
      mountPath: /export/
