apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lotusboot-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lotusboot-storage-paramcache-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lotusboot-node-paramcache-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: lotusboot
spec:
  tolerations:
  - key: lotus
    effect: NoSchedule
    operator: Equal
    value: boot
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: lotusboot-data-pvc
  - name: node-paramcache
    persistentVolumeClaim:
      claimName: lotusboot-node-paramcache-pvc
  - name: storage-paramcache
    persistentVolumeClaim:
      claimName: lotusboot-storage-paramcache-pvc
  containers:
  - name: lotusboot
    image: harbor.filcloud.io:2443/filcloud/lotus-private-boot:latest
    imagePullPolicy: Always
    command: ["bash"]
    #command: ["./lotus"]
    args: ["-c","if [ ! -d \"/data/lotus\" ]; then cp -r /root/.lotus /data/lotus; fi && ./lotus daemon --bootstrap=false"]
    env:
      - name: LOTUS_STORAGE_PATH
        value: /data/lotusstorage
      - name: LOTUS_PATH
        value: /data/lotus
      - name: FULLNODE_LISTEN_ADDR
        value: /ip4/0.0.0.0/tcp/1234/http
      - name: IPFS_GATEWAY
        value: http://10.98.244.47:8080/ipfs/
    volumeMounts:
    - name: data
      mountPath: /data/
    - name: node-paramcache
      mountPath: /var/tmp/filecoin-proof-parameters
  - name: lotusboot-storage-miner
    image: harbor.filcloud.io:2443/filcloud/lotus-private:latest
    imagePullPolicy: Always
    command: ["bash"]
    args: ["-c","if [ ! -d "/data/lotusstorage" ]; then ./lotus-storage-miner init --actor=t0101 --genesis-miner; fi && ./lotus-storage-miner run"]
    env:
      - name: LOTUS_STORAGE_PATH
        value: /data/lotusstorage
      - name: LOTUS_PATH
        value: /data/lotus
      - name: FULLNODE_LISTEN_ADDR
        value: /ip4/0.0.0.0/tcp/1234/http
      - name: FULLNODE_API
        value: /dns4/lotusboot/tcp/1234/http
      - name: FULLNODE_TOKEN
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.ijPwSQ73R6w2RikQQai0U5_QpY4XmnJXoQGjVo2ULos
      - name: IPFS_GATEWAY
        value: http://10.98.244.47:8080/ipfs/
    volumeMounts:
    - name: data
      mountPath: /data/
    - name: storage-paramcache
      mountPath: /var/tmp/filecoin-proof-parameters
