apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lotus01-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lotusstorage01-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: lotus01
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: lotus01-pvc
  containers:
  - name: lotus01
    image: harbor.filcloud.io:2443/filcloud/lotus:latest
    env:
      - name: LOTUS_STORAGE_PATH
        value: /data/lotusstorage
      - name: LOTUS_PATH
        value: /data/lotus
    volumeMounts:
    - name: data
      mountPath: /data/
