apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lotus
spec:
  selector:
    matchLabels:
      app: lotus
  template:
    metadata:
      name: lotus-app
      labels:
        app: lotus
    spec:
      volumes:
      - name: data
        hostPath:
          path: /data
      - name: paramcache
        hostPath:
          path: /paramcache
      containers:
      - name: lotus
        image: harbor.filcloud.io:2443/filcloud/lotus:latest
        imagePullPolicy: Always
        command: ["./lotus"]
        args: ["daemon"]
        env:
          - name: LOTUS_PATH
            value: /data/lotus
          - name: FULLNODE_LISTEN_ADDR
            value: /ip4/0.0.0.0/tcp/1234/http
          - name: IPFS_GATEWAY
            value: http://10.98.244.47:8080/ipfs/
          - name: PROXY_FETCHER_ADDR
            value: ${PROXYLOCK_SERVICE_HOST}
        volumeMounts:
          - name: data
            mountPath: /data/
          - name: paramcache
            mountPath: /var/tmp/filecoin-proof-parameters
      - name: lotus-storage-miner
        image: harbor.filcloud.io:2443/filcloud/lotus:latest
        imagePullPolicy: Always
        command: ["bash","-c", "echo \"waiting 300 seconds\" && sleep 300 && while true; do if [ -d \"/data/lotusstorage\" ]; then break; fi; echo \"waiting for storage miner initialization\" && sleep 5; done && echo \"sleep more 30 second before storage miner running\" && sleep 30 && ./lotus-storage-miner run"]
        env:
          - name: LOTUS_PATH
            value: /data/lotus
          - name: LOTUS_STORAGE_PATH
            value: /data/lotusstorage
          - name: FULLNODE_LISTEN_ADDR
            value: /ip4/0.0.0.0/tcp/1234/http
# masked because of local repo mode instead of remote mode is used 
#          - name: FULLNODE_API
#            value: /dns4/lotus/tcp/1234/http
#          - name: FULLNODE_TOKEN
#            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.FTCrFuANxnafCaLLefICZ7hZ0CjZz40hgyQj90QIfdo
          - name: IPFS_GATEWAY
            value: http://10.98.244.47:8080/ipfs/
        volumeMounts:
        - name: data
          mountPath: /data/
        - name: paramcache
          mountPath: /var/tmp/filecoin-proof-parameters
      - name: lotus-helper
        image: harbor.filcloud.io:2443/filcloud/lotus:latest
        imagePullPolicy: Always
        command: ["bash","-c", "echo \"waiting 300 seconds\" && sleep 300 && if [ ! -d \"/data/lotusstorage\" ]; then ./lotus sync status && echo \"waiting for sync ...\" && ./lotus sync wait && echo \"running lotus-helper\" && ./lotus-helper run; fi"]
        env:
          - name: LOTUS_PATH
            value: /data/lotus
          - name: LOTUS_STORAGE_PATH
            value: /data/lotusstorage
          - name: IPFS_GATEWAY
            value: http://10.98.244.47:8080/ipfs/
        volumeMounts:
        - name: data
          mountPath: /data/
        - name: paramcache
          mountPath: /var/tmp/filecoin-proof-parameters
